version: '3.3'

services:

  cp-client-app:
    image: registry.coinpush.app/client-app
    container_name: client-app
    build:
      context: .
      dockerfile: ./client-app/Dockerfile
    volumes:
      - .:/usr/src/app/client-app