version: '3.3'

services:

  cp-client-web:
    environment:
      - NODE_ENV=development
    ports:
      - 4200:4200
    command: npm start
    volumes:
       - ./src:/usr/src/app/src

volumes:
  mongodata: